Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "MyAppPipeline"
      RoleArn: !ImportValue PipelineRoleARN
      ArtifactStore:
        Type: S3
        Location: my-artifact-bucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                RepositoryName: "imkam94/Devops_Challenge"
                BranchName: "main"
                OAuthToken: !Sub "{{resolve:secretsmanager:GitHubToken}}"
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: Devops
        - Name: Deploy
          Actions:
            - Name: LambdaDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: Lambda
                Version: "1"
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                FunctionName: helm-deploy-function
