trigger:
  branches:
    include:
      - main
  paths:
    include:
      - application/**
      - infrastructure/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_IMAGE: '580197165862.dkr.ecr.us-west-2.amazonaws.com/devops'
  KUBECONFIG: $(System.DefaultWorkingDirectory)/kubeconfig

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Set Python Version'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-ecr-connection'
  displayName: 'Login to AWS'

- script: |
    $(aws ecr get-login-password --region us-west-2) | docker login --username AWS --password-stdin $(DOCKER_IMAGE)
    docker build -t $(DOCKER_IMAGE):latest .
    docker push $(DOCKER_IMAGE):latest
  displayName: 'Build and Push Docker Image to ECR'

- task: HelmDeploy@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    namespace: 'default'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: helm-chart/
    releaseName: 'my-app'
    overrideValues: 'image.repository=$(DOCKER_IMAGE),image.tag=latest'
  displayName: 'Deploy Application to EKS'
