trigger:
  branches:
    include:
      - main
  paths:
    include:
      - application/**
      - infrastructure/**

pool:
  vmImage: 'Azure Pipelines'

variables:
  DOCKER_REPO: '580197165862.dkr.ecr.us-west-2.amazonaws.com/devops'
  KUBECONFIG: $(System.DefaultWorkingDirectory)/kubeconfig

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: 'Set Python Version'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-ecr-connection'
  displayName: 'Login to AWS'

- script: |
    aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 580197165862.dkr.ecr.us-west-2.amazonaws.com
    docker build -t $(DOCKER_REPO):latest -f ./application/Dockerfile ./application
    docker push $(DOCKER_REPO):latest
  displayName: 'Build and Push Docker Image to ECR'

#- task: HelmDeploy@1
#  inputs:
#    connectionType: 'Kubernetes Service Connection'
#    namespace: 'default'
#    command: 'upgrade'
#    chartType: 'FilePath'
#    chartPath: helm-chart/
#    releaseName: 'my-app'
#    overrideValues: 'image.repository=$(DOCKER_REPO),image.tag=latest'
#  displayName: 'Deploy Application to EKS'
