AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC for EKS Cluster"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs ""]

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "EKS security group"
      VpcId: !Ref VPC
    SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"  
        - IpProtocol: "tcp"
          FromPort: "10250"
          ToPort: "10250"
          CidrIp: "0.0.0.0/0" 
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"  

Outputs:
  VPCID:
    Value: !Ref VPC
    Export:
      Name: VPC-ID

  SubnetIDs:
    Value: !Join [",", [!Ref Subnet1, !Ref Subnet2]]
    Export:
      Name: VPC-SubnetIDs

  SecurityGroupID:
    Value: !Ref SecurityGroup
    Export:
      Name: VPC-SecurityGroupID
