apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  labels:
    app: rest-api
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    app: rest-api

